%% Part 5e
run('p5p5d.m');
sim('p5p5ex');

%{
genPlotFile('Part_5_5_e', 'Measured compass course (with bias estimate feed forward and wave filtering)', 'time [s]', ...
    'Heading [deg]', psi_measured.time, psi_measured.data, psi_hat.data, ...
    '$\psi$ (Measured compass course)', '$\hat{\psi}$ (Estimated compass course)');

genPlotFile('Part_5_5_e', 'Estimated bias and rudder input', 'time [s]', ...
    'Rudder angle [deg]', b_hat.time, b_hat.data, delta.data, ...
    '$\hat{b}$ (Estimated bias)', '${u}$ (Rudder input)');

genPlotFile('Part_5_5_e', 'Wave influence', 'time [s]', ...
    'Heading [deg]', psi_w_hat.time, psi_w.data, psi_w_hat.data, ...
    '$\psi_w$ (Wave influence)', '$\hat{\psi}_w$ (Estimated wave influence)');
%}